import { getCredential, getSetting, putCache, cacheError, putCredential, markCredential } from '../state.ts'
import { ProviderError, request } from '../provider-http.ts'
import { maskSecret, nowIso, numberValue, text } from '../util.ts'

const base=()=>text(getSetting('chmlfrp.base_url','https://cf-v2.uapis.cn')).replace(/\/$/,'')
const timeout=()=>Number(getSetting('chmlfrp.timeout_ms',20000))
function access(){const value=getCredential('chmlfrp','access_token');if(!value)throw new ProviderError('CHMLFRP_ACCESS_MISSING','没有ChmlFrp Access Token',400);return value}
function clientBasic(){const clientId=getCredential('chmlfrp','client_id')||text(getSetting('chmlfrp.oauth.client_id',''));const secret=getCredential('chmlfrp','client_secret');if(!clientId)throw new ProviderError('CHMLFRP_CLIENT_MISSING','请配置OAuth client_id',400);return {clientId,header:`Basic ${Buffer.from(`${clientId}:${secret}`).toString('base64')}`}}
export async function refreshToken(){const refresh=getCredential('chmlfrp','refresh_token');if(!refresh)throw new ProviderError('CHMLFRP_REFRESH_MISSING','没有Refresh Token',400);const {header}=clientBasic();const body=new URLSearchParams({grant_type:'refresh_token',refresh_token:refresh});const scope=text(getSetting('chmlfrp.oauth.scope',''));if(scope)body.set('scope',scope);const result=await request(text(getSetting('chmlfrp.oauth.token_url','https://account-api.qzhua.net/oauth2/token')),{method:'POST',headers:{authorization:header,'content-type':'application/x-www-form-urlencoded',accept:'application/json'},body,timeoutMs:timeout()});return saveTokenResponse(result.json,'refresh')}
function saveTokenResponse(data:any,source:string){if(!data?.access_token)throw new ProviderError('CHMLFRP_TOKEN_INVALID','OAuth响应没有access_token',502,data);const expiresAt=data.expires_in?new Date(Date.now()+Number(data.expires_in)*1000).toISOString():null;putCredential('chmlfrp','access_token',data.access_token,{source,expiresAt,tokenType:data.token_type||'Bearer',scope:data.scope||null});if(data.refresh_token)putCredential('chmlfrp','refresh_token',data.refresh_token,{source,rotatedAt:nowIso()});return {saved:true,accessTokenMask:maskSecret(data.access_token),expiresAt,refreshTokenRotated:!!data.refresh_token,scope:data.scope||null}}
export async function validateLogin(){const token=access();const result=await request(`${base()}/login?access_token=${encodeURIComponent(token)}`,{timeoutMs:timeout()});if(result.json?.code!==200)throw new ProviderError('CHMLFRP_LOGIN_FAILED',text(result.json?.msg)||'ChmlFrp登录校验失败',401,result.json);markCredential('chmlfrp','access_token',true);putCache('chmlfrp.login','chmlfrp',result.json,120);return result.json}
export async function ensureAuth(){try{return {mode:'access_token',data:await validateLogin()}}catch(first){try{await refreshToken();return {mode:'refresh_token',data:await validateLogin()}}catch(second){throw new ProviderError('CHMLFRP_AUTH_REQUIRED','Access Token和Refresh Token均不可用，需要人工或Device授权',401,{first:first instanceof Error?first.message:first,second:second instanceof Error?second.message:second})}}}
export async function startDeviceFlow(){const url=text(getSetting('chmlfrp.oauth.device_authorization_url',''));if(!url)throw new ProviderError('DEVICE_FLOW_NOT_CONFIGURED','未配置Device Authorization URL',400);const {clientId}=clientBasic();const body=new URLSearchParams({client_id:clientId});const scope=text(getSetting('chmlfrp.oauth.scope',''));if(scope)body.set('scope',scope);const result=await request(url,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded',accept:'application/json'},body,timeoutMs:timeout()});if(!result.json?.device_code||!result.json?.user_code)throw new ProviderError('DEVICE_FLOW_INVALID','Device Code响应缺少字段',502,result.json);return result.json}
export async function pollDevice(deviceCode:string){const {header,clientId}=clientBasic();const body=new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:device_code',device_code:deviceCode,client_id:clientId});const result=await request(text(getSetting('chmlfrp.oauth.token_url','https://account-api.qzhua.net/oauth2/token')),{method:'POST',headers:{authorization:header,'content-type':'application/x-www-form-urlencoded',accept:'application/json'},body,timeoutMs:timeout()});return saveTokenResponse(result.json,'device')}
export function manualTokens(accessToken:string,refreshToken?:string,expiresAt?:string){putCredential('chmlfrp','access_token',accessToken,{source:'manual',expiresAt:expiresAt||null});if(refreshToken)putCredential('chmlfrp','refresh_token',refreshToken,{source:'manual'});return {saved:true,mask:maskSecret(accessToken)}}
export async function listNodesRaw(){await ensureAuth();const result=await request(`${base()}/node`,{headers:{authorization:`Bearer ${access()}`,accept:'application/json'},timeoutMs:timeout()});const data=Array.isArray(result.json)?result.json:result.json?.data||[];putCache('chmlfrp.nodes.raw','chmlfrp',data,300);return data}
export async function nodeInfo(name:string){const result=await request(`${base()}/nodeinfo?token=${encodeURIComponent(access())}&node=${encodeURIComponent(name)}`,{timeoutMs:timeout()});if(result.json?.code&&result.json.code!==200)throw new ProviderError('CHMLFRP_NODEINFO_FAILED',text(result.json?.msg)||'节点状态读取失败',502,result.json);return result.json?.data||result.json}
export async function listTunnelsRaw(){await ensureAuth();try{const result=await request(`${base()}/tunnel`,{headers:{authorization:`Bearer ${access()}`,accept:'application/json'},timeoutMs:timeout()});const data=Array.isArray(result.json)?result.json:result.json?.data||[];putCache('chmlfrp.tunnels.raw','chmlfrp',data,180);return data}catch(e){cacheError('chmlfrp.tunnels.raw','chmlfrp',e instanceof Error?e.message:'隧道读取失败');throw e}}
export function normalizeNode(raw:any){const name=text(raw.name||raw.node||raw.nodeName||raw.node_name||raw.label);return {externalId:text(raw.id||raw.nodeID||raw.nodeId),name,displayName:text(raw.displayName||raw.chinaName||raw.cn_name)||name,region:text(raw.region||raw.area||raw.location||raw.nodegroup),endpoint:text(raw.endpoint||raw.ip||raw.host||raw.serverAddr),realIp:text(raw.realIp||raw.real_ip),serverPort:numberValue(raw.serverPort||raw.port||raw.frpPort||raw.frpsPort,0)||null,online:String(raw.state||raw.status||'').toLowerCase()==='online'||raw.online===true,webSupported:Boolean(raw.webSupported||raw.web_supported||raw.wed||raw.http||raw.https),metadata:raw}}
export function normalizeTunnel(raw:any){const prefix=text(getSetting('chmlfrp.managed_prefix','[ashan-frp]'));const name=text(raw.name||raw.tunnelName||raw.tunnel_name);return {externalId:text(raw.id||raw.tunnelID||raw.tunnelId),name,nodeName:text(raw.node||raw.nodeName||raw.node_name),protocol:text(raw.type||raw.protocol||raw.portType).toLowerCase(),localIp:text(raw.localip||raw.localIP||raw.local_ip)||'127.0.0.1',localPort:numberValue(raw.nport||raw.localPort||raw.local_port),remotePort:numberValue(raw.remoteport||raw.remotePort||raw.remote_port||(/^(tcp|udp)$/i.test(raw.type||raw.protocol)?raw.dorp:0))||null,domain:text(raw.banddomain||raw.bandDomain||raw.domain||(!/^(tcp|udp)$/i.test(raw.type||raw.protocol)?raw.dorp:'')),remoteIp:text(raw.realIp||raw.remoteIp||raw.ip),managed:name.startsWith(prefix),raw}}
export async function createTunnel(input:any,nodeName:string){const prefix=text(getSetting('chmlfrp.managed_prefix','[ashan-frp]'));const tunnelName=text(input.name).startsWith(prefix)?text(input.name):`${prefix}${text(input.name)}`;const body={token:access(),tunnelname:tunnelName,node:nodeName,localip:text(input.localIp||input.local_ip)||'127.0.0.1',porttype:text(input.protocol||input.porttype).toLowerCase(),localport:numberValue(input.localPort||input.local_port),remoteport:numberValue(input.remotePort||input.remote_port),banddomain:text(input.domain||input.banddomain),encryption:Boolean(input.encryption),compression:input.compression!==false,extraparams:text(input.extraParams||input.extra_params)};const result=await request(`${base()}/create_tunnel`,{method:'POST',headers:{'content-type':'application/json',accept:'application/json'},body:JSON.stringify(body),timeoutMs:timeout()});if(result.json?.code&&![200,201].includes(Number(result.json.code)))throw new ProviderError('CHMLFRP_CREATE_FAILED',text(result.json.msg||result.json.message)||'创建隧道失败',502,result.json);return result.json||result.text}
export async function deleteTunnel(externalId:string){const result=await request(`${base()}/delete_tunnel?tunnelid=${encodeURIComponent(externalId)}`,{headers:{authorization:`Bearer ${access()}`,accept:'application/json'},timeoutMs:timeout()});const msg=text(result.json?.msg||result.json?.message||result.text);if(result.json?.code&&Number(result.json.code)!==200&&!/不存在|不属于/.test(msg))throw new ProviderError('CHMLFRP_DELETE_FAILED',msg||'删除隧道失败',502,result.json);return {deleted:true,message:msg}}
export async function getConfig(nodeName:string){const result=await request(`${base()}/tunnel_config?token=${encodeURIComponent(access())}&node=${encodeURIComponent(nodeName)}`,{timeoutMs:timeout()});let value='';if(typeof result.json?.data==='string')value=result.json.data;else if(!result.json)value=result.text;else if(typeof result.json==='string')value=result.json;if(!value||/失败|error/i.test(value.slice(0,100)))throw new ProviderError('CHMLFRP_CONFIG_FAILED','未获取到有效frpc配置',502,result.json||result.text);return value}
