import { getCredential, getSetting, putCache, cacheError } from '../state.ts'
import { ProviderError, request } from '../provider-http.ts'
import { text } from '../util.ts'
const base=()=>text(getSetting('cloudflare.api_base','https://api.cloudflare.com/client/v4')).replace(/\/$/,'')
function headers():Record<string,string>{const token=getCredential('cloudflare','api_token');if(token)return {authorization:`Bearer ${token}`,'content-type':'application/json'};const key=getCredential('cloudflare','global_api_key'),email=getCredential('cloudflare','account_email');if(key&&email)return {'x-auth-key':key,'x-auth-email':email,'content-type':'application/json'};throw new ProviderError('CLOUDFLARE_CREDENTIALS_MISSING','请保存Cloudflare API Token，或Global API Key和邮箱',400)}
async function cf(path:string,init:RequestInit={}):Promise<any>{const result=await request(`${base()}${path}`,{...init,headers:{...headers(),...(init.headers||{})},timeoutMs:20000});if(!result.json?.success)throw new ProviderError('CLOUDFLARE_API_ERROR',(result.json?.errors||[]).map((x:any)=>x.message).join('；')||'Cloudflare API错误',502,result.json);return result.json}
export async function zones(){const data=await cf('/zones?per_page=50');putCache('cloudflare.zones','cloudflare',data.result,600);return data.result}
export async function zoneId(){let id=text(getSetting('cloudflare.zone_id',''));if(id)return id;const list=await zones();if(list.length===1)return list[0].id;throw new ProviderError('CLOUDFLARE_ZONE_REQUIRED','请在设置中选择Zone',400,{zones:list.map((x:any)=>({id:x.id,name:x.name}))})}
export async function testCloudflare(){try{const list=await zones();return {connected:true,zones:list.map((x:any)=>({id:x.id,name:x.name,status:x.status}))}}catch(e){cacheError('cloudflare.connection','cloudflare',e instanceof Error?e.message:'Cloudflare连接失败');throw e}}
export async function listDns(){const zid=await zoneId();const data=await cf(`/zones/${zid}/dns_records?per_page=500`);putCache('cloudflare.dns.raw','cloudflare',data.result,180);return data.result}
export async function createDns(record:any){const zid=await zoneId();const payload={type:record.type,name:record.name,content:record.content,ttl:Number(record.ttl||1),proxied:Boolean(record.proxied)};return (await cf(`/zones/${zid}/dns_records`,{method:'POST',body:JSON.stringify(payload)})).result}
export async function updateDns(externalId:string,record:any){const zid=await zoneId();const payload={type:record.type,name:record.name,content:record.content,ttl:Number(record.ttl||1),proxied:Boolean(record.proxied)};return (await cf(`/zones/${zid}/dns_records/${externalId}`,{method:'PUT',body:JSON.stringify(payload)})).result}
export async function deleteDns(externalId:string){const zid=await zoneId();return (await cf(`/zones/${zid}/dns_records/${externalId}`,{method:'DELETE'})).result}
