import { randomBytes } from 'node:crypto'
import type { IncomingMessage } from 'node:http'
import { all, one, run } from './db.ts'
import { config } from './config.ts'
import { hashPassword, tokenHash, verifyPassword } from './security.ts'
import { id, nowIso } from './util.ts'

function cookie(req:IncomingMessage,name:string):string{ for(const part of String(req.headers.cookie||'').split(';')){ const [key,...rest]=part.trim().split('='); if(key===name) return decodeURIComponent(rest.join('=')) } return '' }
export function setupRequired():boolean{return !one('SELECT id FROM admin_users LIMIT 1')}
export function createAdmin(username:string,password:string,displayName:string):any{ if(!setupRequired()) throw Object.assign(new Error('管理员已存在'),{code:'ADMIN_EXISTS',status:409}); if(username.length<3||password.length<10) throw Object.assign(new Error('用户名至少3位，密码至少10位'),{code:'INPUT_INVALID',status:400}); const p=hashPassword(password), uid=id(), now=nowIso(); run('INSERT INTO admin_users(id,username,display_name,password_hash,password_salt,created_at,updated_at) VALUES(?,?,?,?,?,?,?)',uid,username,displayName||username,p.hash,p.salt,now,now); return {id:uid,username,displayName:displayName||username} }
export function login(username:string,password:string,req:IncomingMessage):{token:string;session:any}{ const user=one('SELECT * FROM admin_users WHERE username=?',username); if(!user||!verifyPassword(password,user.password_salt,user.password_hash)) throw Object.assign(new Error('用户名或密码错误'),{code:'LOGIN_FAILED',status:401}); const raw=randomBytes(32).toString('base64url'), sid=id(), csrf=randomBytes(24).toString('base64url'), now=nowIso(), expires=new Date(Date.now()+config.sessionTtlHours*3600000).toISOString(); run('INSERT INTO sessions(id,user_id,token_hash,csrf_token,created_at,expires_at,last_seen_at,user_agent,ip_address) VALUES(?,?,?,?,?,?,?,?,?)',sid,user.id,tokenHash(raw),csrf,now,expires,now,String(req.headers['user-agent']||''),String(req.socket.remoteAddress||'')); run('UPDATE admin_users SET last_login_at=?,updated_at=? WHERE id=?',now,now,user.id); return {token:raw,session:{id:sid,user:{id:user.id,username:user.username,displayName:user.display_name},csrfToken:csrf,expiresAt:expires}} }
export function authenticateRequest(req:IncomingMessage):any{ const raw=cookie(req,'ashan_frp_session'); if(!raw) return null; const row=one(`SELECT s.*,u.username,u.display_name FROM sessions s JOIN admin_users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?`,tokenHash(raw),nowIso()); if(!row) return null; run('UPDATE sessions SET last_seen_at=? WHERE id=?',nowIso(),row.id); return {id:row.user_id,username:row.username,displayName:row.display_name,sessionId:row.id,csrfToken:row.csrf_token,expiresAt:row.expires_at} }
export function requireCsrf(req:IncomingMessage,user:any):void{ const token=String(req.headers['x-csrf-token']||''); if(!token||token!==user.csrfToken) throw Object.assign(new Error('CSRF校验失败'),{code:'CSRF_FAILED',status:403}) }
export function logout(req:IncomingMessage):void{ const raw=cookie(req,'ashan_frp_session'); if(raw) run('DELETE FROM sessions WHERE token_hash=?',tokenHash(raw)) }
export function verifyAdminPassword(userId:string,password:string):boolean{ const user=one('SELECT * FROM admin_users WHERE id=?',userId); return !!user&&verifyPassword(password,user.password_salt,user.password_hash) }
export function changePassword(userId:string,current:string,next:string):void{ if(next.length<10) throw Object.assign(new Error('新密码至少10位'),{code:'PASSWORD_WEAK',status:400}); if(!verifyAdminPassword(userId,current)) throw Object.assign(new Error('当前密码错误'),{code:'PASSWORD_INVALID',status:403}); const p=hashPassword(next); run('UPDATE admin_users SET password_hash=?,password_salt=?,updated_at=? WHERE id=?',p.hash,p.salt,nowIso(),userId); run('DELETE FROM sessions WHERE user_id=?',userId) }
export function cleanupSessions():void{run('DELETE FROM sessions WHERE expires_at<=?',nowIso())}
export function sessionCount():number{return Number(one('SELECT COUNT(*) AS n FROM sessions')?.n||0)}
