import { all, one, run } from './db.ts'
import { decrypt, encrypt } from './security.ts'
import { id, json, maskSecret, nowIso, redact, sha256 } from './util.ts'

export function getSetting<T>(key: string, fallback: T): T { const row=one('SELECT value_json FROM settings WHERE key=?',key); return row ? json(row.value_json,fallback) : fallback }
export function setSetting(key: string, value: unknown, actor?: string): void { run('INSERT INTO settings(key,value_json,updated_at,updated_by) VALUES(?,?,?,?) ON CONFLICT(key) DO UPDATE SET value_json=excluded.value_json,updated_at=excluded.updated_at,updated_by=excluded.updated_by',key,JSON.stringify(value),nowIso(),actor||null) }
export function listSettings(): Record<string,unknown> { return Object.fromEntries(all('SELECT key,value_json FROM settings ORDER BY key').map((row)=>[row.key,json(row.value_json,null)])) }
export function putCredential(provider: string,name: string,secret: string,metadata: Record<string,unknown>={}): any {
  const existing=one('SELECT id,revision,created_at FROM credentials WHERE provider=? AND name=?',provider,name), now=nowIso(), cid=existing?.id||id(), revision=(existing?.revision||0)+1
  run('INSERT INTO credentials(id,provider,name,secret_ciphertext,metadata_json,status,revision,created_at,updated_at,last_error) VALUES(?,?,?,?,?,?,?,?,?,NULL) ON CONFLICT(provider,name) DO UPDATE SET secret_ciphertext=excluded.secret_ciphertext,metadata_json=excluded.metadata_json,status=\'configured\',revision=excluded.revision,updated_at=excluded.updated_at,last_error=NULL',cid,provider,name,encrypt(secret),JSON.stringify(metadata), 'configured',revision,existing?.created_at||now,now)
  return { id:cid,provider,name,mask:maskSecret(secret),fingerprint:sha256(secret).slice(0,12),revision,updatedAt:now,metadata }
}
export function getCredential(provider:string,name:string): string { const row=one('SELECT secret_ciphertext FROM credentials WHERE provider=? AND name=?',provider,name); return row ? decrypt(row.secret_ciphertext) : '' }
export function listCredentials(): any[] { return all('SELECT * FROM credentials ORDER BY provider,name').map((row)=>{ let value=''; try{value=decrypt(row.secret_ciphertext)}catch{}; return {id:row.id,provider:row.provider,name:row.name,status:row.status,revision:row.revision,mask:maskSecret(value),fingerprint:value?sha256(value).slice(0,12):'',metadata:json(row.metadata_json,{}),updatedAt:row.updated_at,lastValidatedAt:row.last_validated_at,lastError:row.last_error} }) }
export function markCredential(provider:string,name:string,ok:boolean,error=''): void { run('UPDATE credentials SET status=?,last_validated_at=?,last_error=? WHERE provider=? AND name=?',ok?'valid':'error',ok?nowIso():null,error||null,provider,name) }
export function deleteCredential(provider:string,name:string): void { run('DELETE FROM credentials WHERE provider=? AND name=?',provider,name) }
export function putCache(key:string,provider:string,value:unknown,ttlSeconds=60,status='fresh'):void { const now=nowIso(), expires=new Date(Date.now()+ttlSeconds*1000).toISOString(), count=Array.isArray(value)?value.length:0; run('INSERT INTO cache_entries(key,provider,value_json,status,record_count,payload_hash,updated_at,expires_at,last_error) VALUES(?,?,?,?,?,?,?,?,NULL) ON CONFLICT(key) DO UPDATE SET provider=excluded.provider,value_json=excluded.value_json,status=excluded.status,record_count=excluded.record_count,payload_hash=excluded.payload_hash,updated_at=excluded.updated_at,expires_at=excluded.expires_at,last_error=NULL',key,provider,JSON.stringify(value),status,count,sha256(JSON.stringify(value)),now,expires) }
export function cacheError(key:string,provider:string,error:string):void { const existing=one('SELECT value_json,record_count,payload_hash FROM cache_entries WHERE key=?',key); run('INSERT INTO cache_entries(key,provider,value_json,status,record_count,payload_hash,updated_at,expires_at,last_error) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(key) DO UPDATE SET status=\'unavailable\',updated_at=excluded.updated_at,last_error=excluded.last_error',key,provider,existing?.value_json||'null','unavailable',existing?.record_count||0,existing?.payload_hash||null,nowIso(),null,error) }
export function audit(actor:string|undefined,action:string,targetType:string|undefined,targetId:string|undefined,outcome:string,details:unknown={},requestId?:string):void { run('INSERT INTO audit_logs(id,actor_user_id,action,target_type,target_id,outcome,request_id,details_json,created_at) VALUES(?,?,?,?,?,?,?,?,?)',id(),actor||null,action,targetType||null,targetId||null,outcome,requestId||null,JSON.stringify(redact(details)),nowIso()) }
