version: 2
multi-ecosystem-groups:
  project-dependencies:
    schedule:
      interval: weekly
    labels:
      - dependencies
updates:
  - package-ecosystem: cargo
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: project-dependencies

  - package-ecosystem: github-actions
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: project-dependencies

  - package-ecosystem: docker
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: project-dependencies
