import { all, one, run, transaction } from '../db.ts'
import { createDns, deleteDns, listDns, updateDns } from '../providers/cloudflare.ts'
import { getSetting, putCache } from '../state.ts'
import { id, json, nowIso, sha256, text } from '../util.ts'

export function listDesiredDns(){return all('SELECT * FROM desired_dns ORDER BY name,type').map((r)=>({...r,proxied:!!r.proxied,enabled:!!r.enabled,managed:!!r.managed}))}
export function listObservedDns(){return all('SELECT * FROM observed_dns ORDER BY name,type').map((r)=>({...r,proxied:!!r.proxied,managed:!!r.managed,raw:json(r.raw_json,{})}))}
export function saveDesiredDns(input:any){
  const name=text(input.name),type=text(input.type||'CNAME').toUpperCase(),content=text(input.content)
  if(!name||!content)throw Object.assign(new Error('DNS名称和内容不能为空'),{code:'DNS_INPUT_INVALID',status:400})
  if(!['A','AAAA','CNAME','TXT','MX','CAA'].includes(type))throw Object.assign(new Error('不支持的DNS记录类型'),{code:'DNS_TYPE_INVALID',status:400})
  const ttl=Number(input.ttl||1)
  if(!Number.isInteger(ttl)||ttl<1)throw Object.assign(new Error('TTL必须为正整数'),{code:'DNS_TTL_INVALID',status:400})
  const requestedId=text(input.id),byId=requestedId?one('SELECT * FROM desired_dns WHERE id=?',requestedId):null
  if(requestedId&&!byId)throw Object.assign(new Error('期望DNS记录不存在'),{code:'DESIRED_DNS_NOT_FOUND',status:404})
  const byKey=one('SELECT * FROM desired_dns WHERE name=? AND type=?',name,type)
  if(byKey&&byId&&byKey.id!==byId.id)throw Object.assign(new Error('同名同类型DNS记录已存在'),{code:'DNS_KEY_CONFLICT',status:409})
  const existing=byId||byKey,did=existing?.id||id(),now=nowIso()
  const values=[name,type,content,input.proxied?1:0,ttl,input.enabled===false?0:1,input.managed===false?0:1,input.sourceTunnelId||input.source_tunnel_id||null,text(input.comment)||null,now,did]
  if(existing)run('UPDATE desired_dns SET name=?,type=?,content=?,proxied=?,ttl=?,enabled=?,managed=?,source_tunnel_id=?,comment=?,updated_at=? WHERE id=?',...values)
  else run('INSERT INTO desired_dns(id,name,type,content,proxied,ttl,enabled,managed,source_tunnel_id,comment,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',did,...values.slice(0,9),now,now)
  return one('SELECT * FROM desired_dns WHERE id=?',did)
}
export function deleteDesiredDns(idValue:string){const result=run('DELETE FROM desired_dns WHERE id=?',idValue);if(!result.changes)throw Object.assign(new Error('期望DNS记录不存在'),{code:'DESIRED_DNS_NOT_FOUND',status:404});return{deleted:true,id:idValue}}
export function deriveDns(targetNode:string){const template=text(getSetting('cloudflare.target_template','{node}.ip.chmlfrp.cn')),target=template.replaceAll('{node}',targetNode);const tunnels=all(`SELECT * FROM desired_tunnels WHERE enabled=1 AND protocol IN ('http','https') AND domain IS NOT NULL AND domain<>''`);for(const t of tunnels)saveDesiredDns({name:t.domain,type:'CNAME',content:target,proxied:Boolean(getSetting('cloudflare.default_proxied',false)),ttl:1,sourceTunnelId:t.id,comment:'由Ashan FRP隧道自动派生'});return{derived:tunnels.length,target}}
export async function syncObservedDns(){const raw=await listDns(),managedIds=new Set(all('SELECT external_id FROM observed_dns WHERE managed=1').map((r)=>r.external_id)),now=nowIso();transaction(()=>{run('DELETE FROM observed_dns');for(const r of raw)run('INSERT INTO observed_dns(id,external_id,name,type,content,proxied,ttl,managed,raw_json,observed_at) VALUES(?,?,?,?,?,?,?,?,?,?)',id(),r.id,r.name,r.type,r.content,r.proxied?1:0,r.ttl||1,managedIds.has(r.id)?1:0,JSON.stringify(r),now)});putCache('dns.observed','cloudflare',raw,180);return{count:raw.length,records:raw}}
function hash(r:any){return sha256(JSON.stringify({name:r.name,type:r.type,content:r.content,proxied:!!r.proxied,ttl:Number(r.ttl||1)}))}
export function buildDnsPlan(options:{cleanupOrphans?:boolean}={}){const desired=listDesiredDns().filter((x:any)=>x.enabled),observed=listObservedDns(),map=new Map(observed.map((x:any)=>[`${x.name}|${x.type}`,x])),actions:any[]=[],matched:string[]=[];for(const d of desired){const key=`${d.name}|${d.type}`,o=map.get(key);if(!o){actions.push({type:'create',desiredId:d.id,name:d.name,expected:d,risk:'medium',reason:'远端缺失'});continue}map.delete(key);if(hash(d)===hash(o)){matched.push(key);continue}if(o.managed)actions.push({type:'update',desiredId:d.id,name:d.name,externalId:o.external_id,previous:o,expected:d,risk:'medium',reason:'内容不同'});else actions.push({type:'conflict',desiredId:d.id,name:d.name,externalId:o.external_id,previous:o,expected:d,risk:'high',reason:'存在未认领的同名记录'})}for(const [key,o] of map){if(o.managed&&options.cleanupOrphans)actions.push({type:'delete_orphan',name:key,externalId:o.external_id,previous:o,risk:'high',reason:'本地无期望定义'});else if(o.managed)actions.push({type:'orphan',name:key,externalId:o.external_id,previous:o,risk:'low',reason:'仅标记，不自动删除'})}return{id:id(),actions,matched,risk:actions.some((x)=>x.risk==='high')?'high':actions.length?'medium':'low',generatedAt:nowIso()}}
export async function applyDnsPlan(plan:any,event:(type:string,message:string,payload?:any)=>void=()=>{}){if(plan.actions.some((x:any)=>x.type==='conflict'))throw Object.assign(new Error('存在未认领DNS冲突，请先人工认领或修改期望记录'),{code:'DNS_CONFLICT',status:409,details:plan.actions.filter((x:any)=>x.type==='conflict')});const results=[];for(const action of plan.actions){if(action.type==='orphan'){results.push({...action,status:'skipped'});continue}if(action.type==='create'){const desired=one('SELECT * FROM desired_dns WHERE id=?',action.desiredId);event('dns.create',`创建DNS ${desired.name}`,action);const response=await createDns(desired);results.push({...action,status:'succeeded',response});continue}if(action.type==='update'){const desired=one('SELECT * FROM desired_dns WHERE id=?',action.desiredId);event('dns.update',`更新DNS ${desired.name}`,action);const response=await updateDns(action.externalId,desired);results.push({...action,status:'succeeded',response});continue}if(action.type==='delete_orphan'){event('dns.delete',`删除孤儿DNS ${action.name}`,action);await deleteDns(action.externalId);results.push({...action,status:'succeeded'})}}await syncObservedDns();const observed=listObservedDns();for(const r of observed){const desired=one('SELECT id FROM desired_dns WHERE name=? AND type=?',r.name,r.type);if(desired)run('UPDATE observed_dns SET managed=1 WHERE external_id=?',r.external_id)}return{applied:true,results}}
export function claimDns(externalId:string,managed:boolean){run('UPDATE observed_dns SET managed=? WHERE external_id=?',managed?1:0,externalId);return one('SELECT * FROM observed_dns WHERE external_id=?',externalId)}
