import { all, one, run } from '../db.ts'
import { getSetting, putCache } from '../state.ts'
import { ensureAuth } from '../providers/chmlfrp.ts'
import { runtimeStatus } from '../providers/runtime.ts'
import { nodeInfo } from '../providers/chmlfrp.ts'
import { httpProbe, tcpProbe } from './probe.ts'
import { id, nowIso, text } from '../util.ts'

export async function healthCheck(){const layers:any[]=[];let overall='healthy';try{one('SELECT 1 AS ok');layers.push({key:'database',status:'healthy',message:'SQLite正常'})}catch(e){layers.push({key:'database',status:'offline',message:e instanceof Error?e.message:String(e)});overall='offline'}
try{const auth=await ensureAuth();layers.push({key:'chmlfrp_auth',status:'healthy',message:'ChmlFrp认证有效',details:{mode:auth?.mode,userId:auth?.data?.data?.id||auth?.data?.id}})}catch(e){layers.push({key:'chmlfrp_auth',status:'degraded',message:e instanceof Error?e.message:String(e)});if(overall==='healthy')overall='degraded'}
const current=text(getSetting('runtime.current_node',''));if(current){try{const info=await nodeInfo(current);const online=String(info?.state||info?.status||'').toLowerCase()==='online'||info?.online===true;layers.push({key:'node',status:online?'healthy':'offline',message:online?`${current}在线`:`${current}离线`,details:info});if(!online)overall='offline'}catch(e){layers.push({key:'node',status:'offline',message:e instanceof Error?e.message:String(e)});overall='offline'}}else{layers.push({key:'node',status:'degraded',message:'尚未设置当前节点'});if(overall==='healthy')overall='degraded'}
let runtime:any=null;try{runtime=await runtimeStatus();const running=runtime.process?.state==='running';const valid=runtime.validation?.valid;const binary=runtime.binary?.exists;const status=running&&valid&&binary?'healthy':running||valid?'degraded':'offline';layers.push({key:'frpc_runtime',status,message:running?'内置 frpc 进程运行中':'内置 frpc 进程未运行',details:{process:runtime.process,binary:runtime.binary,config:runtime.file,validation:runtime.validation,log:runtime.log}});if(status==='offline')overall='offline';else if(status==='degraded'&&overall==='healthy')overall='degraded'}catch(e){layers.push({key:'frpc_runtime',status:'offline',message:e instanceof Error?e.message:String(e)});overall='offline'}
const tunnels=all(`SELECT * FROM desired_tunnels WHERE enabled=1`),probes:any[]=[];for(const t of tunnels){let result:any;if(t.health_url)result=await httpProbe(t.health_url,Number(getSetting('health.http_timeout_ms',8000)));else if(['http','https'].includes(t.protocol)&&t.domain)result=await httpProbe(`${t.protocol==='https'?'https':'http'}://${t.domain}`,Number(getSetting('health.http_timeout_ms',8000)));else{const observed=one('SELECT * FROM observed_tunnels WHERE name LIKE ? ORDER BY observed_at DESC LIMIT 1',`%${t.name}`);result=observed?.remote_ip&&observed?.remote_port?await tcpProbe(observed.remote_ip,Number(observed.remote_port),Number(getSetting('health.tcp_timeout_ms',3000))):{ok:true,skipped:true,error:'无外部探测地址'}}probes.push({tunnel:t.name,protocol:t.protocol,...result})}
const healthy=probes.filter((p)=>p.ok).length,total=probes.length;if(total){const status=healthy===total?'healthy':healthy===0?'offline':'degraded';layers.push({key:'proxies',status,message:`${healthy}/${total}个代理通过`,details:probes});if(status==='offline')overall='offline';else if(status==='degraded'&&overall==='healthy')overall='degraded'}else{layers.push({key:'proxies',status:'degraded',message:'暂无启用的期望隧道'});if(overall==='healthy')overall='degraded'}
const snapshot={id:id(),overallStatus:overall,layers,proxyTotal:total,proxyHealthy:healthy,nodeName:current||null,createdAt:nowIso()};run('INSERT INTO health_snapshots(id,overall_status,layers_json,proxy_total,proxy_healthy,node_name,created_at) VALUES(?,?,?,?,?,?,?)',snapshot.id,overall,JSON.stringify(layers),total,healthy,current||null,snapshot.createdAt);putCache('health.latest','system',snapshot,120);return snapshot}
export function latestHealth(){const row=one('SELECT * FROM health_snapshots ORDER BY created_at DESC LIMIT 1');return row?{id:row.id,overallStatus:row.overall_status,layers:JSON.parse(row.layers_json),proxyTotal:row.proxy_total,proxyHealthy:row.proxy_healthy,nodeName:row.node_name,createdAt:row.created_at}:null}
