import { all, one, run } from '../db.ts'
import { listNodesRaw, nodeInfo, normalizeNode } from '../providers/chmlfrp.ts'
import { tcpProbe } from './probe.ts'
import { getSetting, putCache } from '../state.ts'
import { clamp, id, json, nowIso, numberValue, text } from '../util.ts'

export async function syncNodes(){const raw=await listNodesRaw(),now=nowIso(),names:string[]=[];for(const item of raw){const n=normalizeNode(item);if(!n.name)continue;names.push(n.name);const existing=one('SELECT id,created_at,failure_count,success_count,ban_until FROM nodes WHERE name=?',n.name);run(`INSERT INTO nodes(id,provider,external_id,name,display_name,region,endpoint,real_ip,server_port,online,web_supported,metadata_json,created_at,updated_at,last_seen_at,failure_count,success_count,ban_until) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(name) DO UPDATE SET external_id=excluded.external_id,display_name=excluded.display_name,region=excluded.region,endpoint=excluded.endpoint,server_port=excluded.server_port,web_supported=excluded.web_supported,metadata_json=excluded.metadata_json,updated_at=excluded.updated_at`,existing?.id||id(),'chmlfrp',n.externalId||null,n.name,n.displayName,n.region||null,n.endpoint||null,n.realIp||null,n.serverPort,n.online?1:0,n.webSupported?1:0,JSON.stringify(n.metadata),existing?.created_at||now,now,n.online?now:existing?.last_seen_at||null,existing?.failure_count||0,existing?.success_count||0,existing?.ban_until||null)}putCache('nodes.normalized','chmlfrp',listNodes(),300);return{synced:names.length,names}}
export function calculateScore(input:{online:boolean;latencyMs:number|null;packetLoss:number|null;failureCount:number;successCount:number;banned:boolean;current:boolean;webSupported:boolean}){let score=100;if(!input.online)score-=500;if(input.banned)score-=1000;if(input.latencyMs!=null)score-=Math.min(70,input.latencyMs/4);if(input.packetLoss!=null)score-=Math.min(60,input.packetLoss*1.5);score-=Math.min(80,input.failureCount*10);score+=Math.min(15,input.successCount*0.5);if(input.current)score+=8;if(input.webSupported)score+=4;return Math.round(score*10)/10}
export async function testNode(name:string){const row=one('SELECT * FROM nodes WHERE name=?',name);if(!row)throw Object.assign(new Error('节点不存在'),{code:'NODE_NOT_FOUND',status:404});let info:any={};let apiOnline=false;try{info=await nodeInfo(name);apiOnline=String(info.state||info.status||'').toLowerCase()==='online'||info.online===true}catch{}const host=text(info.realIp||info.real_ip||row.real_ip||info.ip||row.endpoint);const port=numberValue(info.serverPort||info.port||row.server_port,0);const probe=host&&port?await tcpProbe(host,port,Number(getSetting('health.tcp_timeout_ms',3000))):{ok:apiOnline,latencyMs:0,error:host?'缺少端口':'缺少节点IP'};const online=apiOnline||probe.ok,latency=probe.ok?probe.latencyMs:null,loss=probe.ok?0:100,failures=online?Number(row.failure_count||0):Number(row.failure_count||0)+1,success=online?Number(row.success_count||0)+1:Number(row.success_count||0),banned=!!row.ban_until&&new Date(row.ban_until).getTime()>Date.now(),current=text(getSetting('runtime.current_node',''))===name,score=calculateScore({online,latencyMs:latency,packetLoss:loss,failureCount:failures,successCount:success,banned,current,webSupported:!!row.web_supported});const now=nowIso();run('UPDATE nodes SET real_ip=?,server_port=COALESCE(?,server_port),online=?,latency_ms=?,packet_loss=?,score=?,failure_count=?,success_count=?,last_seen_at=?,last_tested_at=?,metadata_json=?,updated_at=? WHERE id=?',host||row.real_ip,port||null,online?1:0,latency,loss,score,failures,success,online?now:row.last_seen_at,now,JSON.stringify({...json(row.metadata_json,{}),nodeInfo:info,probe}),now,row.id);run('INSERT INTO node_metrics(id,node_id,online,latency_ms,packet_loss,score,reason,measured_at) VALUES(?,?,?,?,?,?,?,?)',id(),row.id,online?1:0,latency,loss,score,probe.error||null,now);return{...row,name,realIp:host,serverPort:port,online,latencyMs:latency,packetLoss:loss,score,probe,nodeInfo:info}}
export async function testAllNodes(limit=20){const rows=all('SELECT name FROM nodes ORDER BY score DESC,name LIMIT ?',limit),results=[];for(const row of rows){try{results.push(await testNode(row.name))}catch(e){results.push({name:row.name,online:false,error:e instanceof Error?e.message:String(e)})}}putCache('nodes.test_results','chmlfrp',results,120);return results}
export function listNodes(){const current=text(getSetting('runtime.current_node',''));return all('SELECT * FROM nodes ORDER BY online DESC,score DESC,name').map((row)=>({...row,online:!!row.online,webSupported:!!row.web_supported,current:row.name===current,banned:!!row.ban_until&&new Date(row.ban_until).getTime()>Date.now(),metadata:json(row.metadata_json,{})}))}
export function bestNode(exclude:string[]=[]){const maxLatency=Number(getSetting('automation.max_latency_ms',250)),maxLoss=Number(getSetting('automation.max_packet_loss',30)),now=nowIso();return all(`SELECT * FROM nodes WHERE online=1 AND name NOT IN (${exclude.length?exclude.map(()=>'?').join(','):'\'\''}) AND (ban_until IS NULL OR ban_until<?) AND (latency_ms IS NULL OR latency_ms<=?) AND (packet_loss IS NULL OR packet_loss<=?) ORDER BY score DESC LIMIT 1`,...exclude,now,maxLatency,maxLoss)[0]||null}
export function banNode(name:string,minutes:number,reason:string){const until=new Date(Date.now()+minutes*60000).toISOString();run('UPDATE nodes SET ban_until=?,failure_count=failure_count+1,metadata_json=?,updated_at=? WHERE name=?',until,JSON.stringify({banReason:reason}),nowIso(),name);return{banned:true,name,until,reason}}
export function clearBan(name:string){run('UPDATE nodes SET ban_until=NULL,updated_at=? WHERE name=?',nowIso(),name)}
