import { all, one, run, transaction } from '../db.ts'
import { getSetting, setSetting } from '../state.ts'
import { bestNode, banNode, testAllNodes } from './nodes.ts'
import { buildTunnelPlan, applyTunnelPlan, syncObservedTunnels } from './tunnels.ts'
import { buildDnsPlan, applyDnsPlan, deriveDns, syncObservedDns, listDesiredDns } from './dns.ts'
import { getConfig, createTunnel, deleteTunnel } from '../providers/chmlfrp.ts'
import { action as runtimeAction, installConfig, restoreConfig } from '../providers/runtime.ts'
import { healthCheck } from './health.ts'
import { id, json, nowIso, text } from '../util.ts'

export async function buildSwitchPlan(targetNode?:string,reason='manual'){await testAllNodes(Number(getSetting('automation.max_candidates',3))+5);const source=text(getSetting('runtime.current_node',''));const target=targetNode?one('SELECT * FROM nodes WHERE name=?',targetNode):bestNode(source?[source]:[]);if(!target)throw Object.assign(new Error('没有可用的候选节点'),{code:'NO_CANDIDATE_NODE',status:409});if(target.name===source)throw Object.assign(new Error('目标节点与当前节点相同'),{code:'TARGET_SAME_AS_SOURCE',status:400});await syncObservedTunnels();try{await syncObservedDns()}catch{}const tunnelPlan=buildTunnelPlan(target.name);const previousDns=listDesiredDns();const dnsTarget=deriveDns(target.name);const derivedDns=listDesiredDns();const dnsPlan=buildDnsPlan();transaction(()=>{run('DELETE FROM desired_dns');for(const d of previousDns)run('INSERT INTO desired_dns(id,name,type,content,proxied,ttl,enabled,managed,source_tunnel_id,comment,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',d.id,d.name,d.type,d.content,d.proxied?1:0,d.ttl,d.enabled?1:0,d.managed?1:0,d.source_tunnel_id||null,d.comment||null,d.created_at,d.updated_at)});const risk=tunnelPlan.actions.some((x:any)=>x.risk==='high')||dnsPlan.actions.some((x:any)=>x.risk==='high')?'high':'medium';const plan={sourceNode:source||null,targetNode:target.name,reason,risk,nodeScore:target.score,tunnelPlan,dnsPlan,dnsTarget,derivedDns,steps:['验证认证和目标节点','保存当前远端隧道及frpc配置快照','按隧道逐条删除旧实例并在目标节点重建','更新受管DNS','下载目标节点frpc.toml','原子安装配置并重启内置 frpc 进程','执行多层健康验证','失败时恢复隧道、DNS和本地配置'],generatedAt:nowIso()};const pid=id();run('INSERT INTO switch_plans(id,source_node,target_node,status,risk,reason,plan_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)',pid,source||null,target.name,'planned',risk,reason,JSON.stringify(plan),nowIso(),nowIso());return{id:pid,...plan}}
export function listSwitchPlans(){return all('SELECT * FROM switch_plans ORDER BY created_at DESC LIMIT 100').map((r)=>({...r,plan:json(r.plan_json,{}),rollback:json(r.rollback_json,{})}))}
export async function executeSwitch(planId:string,event:(type:string,message:string,payload?:any)=>void=()=>{}){const row=one('SELECT * FROM switch_plans WHERE id=?',planId);if(!row)throw Object.assign(new Error('切换计划不存在'),{code:'SWITCH_PLAN_NOT_FOUND',status:404});if(['running','succeeded'].includes(row.status))throw Object.assign(new Error('该计划已执行或正在执行'),{code:'SWITCH_PLAN_STATE_INVALID',status:409});const plan=json<any>(row.plan_json,{}),owner=id(),lockName='failover';const existing=one('SELECT * FROM locks WHERE name=? AND expires_at>?',lockName,nowIso());if(existing)throw Object.assign(new Error('已有切换任务正在运行'),{code:'FAILOVER_LOCKED',status:409});run('INSERT INTO locks(name,owner,expires_at,updated_at) VALUES(?,?,?,?) ON CONFLICT(name) DO UPDATE SET owner=excluded.owner,expires_at=excluded.expires_at,updated_at=excluded.updated_at',lockName,owner,new Date(Date.now()+20*60000).toISOString(),nowIso());run('UPDATE switch_plans SET status=\'running\',executed_at=?,updated_at=? WHERE id=?',nowIso(),nowIso(),planId);let backup:any={};try{event('switch.start',`开始从 ${plan.sourceNode||'未设置'} 切换到 ${plan.targetNode}`);const previousTunnels=await syncObservedTunnels();backup={previousTunnels:previousTunnels.tunnels,previousDesiredDns:listDesiredDns(),sourceNode:plan.sourceNode};event('switch.tunnels','应用隧道切换计划',plan.tunnelPlan);const tunnelResult=await applyTunnelPlan(buildTunnelPlan(plan.targetNode),event);let dnsResult:any=null;try{deriveDns(plan.targetNode);await syncObservedDns();dnsResult=await applyDnsPlan(buildDnsPlan(),event)}catch(e){event('switch.dns.warning','DNS同步失败',{error:e instanceof Error?e.message:String(e)});if(!Boolean(getSetting('switch.allow_dns_failure',false))&&listDesiredDns().length)throw e}
const configContent=await getConfig(plan.targetNode);event('switch.config','已获取目标节点frpc配置');const installed=await installConfig(configContent,plan.targetNode);backup.configBackup=installed.backup;run('INSERT INTO frpc_configs(id,node_name,content,content_hash,source,active,installed_at,created_at) VALUES(?,?,?,?,?,?,?,?)',id(),plan.targetNode,configContent,installed.hash,'chmlfrp',1,nowIso(),nowIso());run('UPDATE frpc_configs SET active=0 WHERE node_name<>?',plan.targetNode);event('switch.runtime','重启内置 frpc 进程');await runtimeAction('restart');await new Promise((r)=>setTimeout(r,5000));setSetting('runtime.current_node',plan.targetNode);const recoveryThreshold=Math.max(1,Number(getSetting('automation.recovery_threshold',2)));const recoveryChecks:any[]=[];for(let attempt=1;attempt<=recoveryThreshold;attempt++){const checked=await healthCheck();recoveryChecks.push(checked);event('switch.verify',`切换后健康验证 ${attempt}/${recoveryThreshold}`,checked);if(checked.overallStatus==='offline')throw Object.assign(new Error('切换后健康验证失败'),{code:'POST_SWITCH_HEALTH_FAILED',details:{attempt,recoveryChecks}});if(attempt<recoveryThreshold)await new Promise((r)=>setTimeout(r,3000))}const health=recoveryChecks[recoveryChecks.length-1];run('UPDATE switch_plans SET status=\'succeeded\',rollback_json=?,completed_at=?,updated_at=? WHERE id=?',JSON.stringify({...backup,recoveryChecks}),nowIso(),nowIso(),planId);run('DELETE FROM locks WHERE name=? AND owner=?',lockName,owner);event('switch.done',`已切换到 ${plan.targetNode}`,health);return{success:true,planId,targetNode:plan.targetNode,tunnelResult,dnsResult,installed,health}}catch(error){event('switch.rollback','切换失败，开始回滚',{error:error instanceof Error?error.message:String(error)});let rollbackError='';try{
  if(Array.isArray(backup.previousDesiredDns)){
    transaction(()=>{run('DELETE FROM desired_dns');for(const d of backup.previousDesiredDns)run('INSERT INTO desired_dns(id,name,type,content,proxied,ttl,enabled,managed,source_tunnel_id,comment,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',d.id,d.name,d.type,d.content,d.proxied?1:0,d.ttl,d.enabled?1:0,d.managed?1:0,d.source_tunnel_id||null,d.comment||null,d.created_at,d.updated_at)})
    try{await syncObservedDns();await applyDnsPlan(buildDnsPlan(),event)}catch(e){rollbackError+=`DNS回滚失败：${e instanceof Error?e.message:String(e)}；`}
  }
  if(Array.isArray(backup.previousTunnels)){
    const current=(await syncObservedTunnels()).tunnels.filter((t:any)=>t.managed)
    const previous=backup.previousTunnels.filter((t:any)=>t.managed)
    const previousByName=new Map(previous.map((t:any)=>[String(t.name),t]))
    for(const t of current){const prior=previousByName.get(String(t.name));if(!prior||prior.nodeName!==t.nodeName){if(t.externalId)await deleteTunnel(t.externalId)}}
    const after=(await syncObservedTunnels()).tunnels
    for(const t of previous){const existing=after.find((x:any)=>x.name===t.name&&x.nodeName===t.nodeName);if(!existing)await createTunnel({name:String(t.name).replace(/^\[ashan-frp\]/,''),protocol:t.protocol,localIp:t.localIp,localPort:t.localPort,remotePort:t.remotePort,domain:t.domain,encryption:false,compression:true,extraParams:''},t.nodeName)}
  }
  if(backup.configBackup){await restoreConfig(backup.configBackup);await runtimeAction('restart')}
  if(plan.sourceNode)setSetting('runtime.current_node',plan.sourceNode)
}catch(e){rollbackError+=e instanceof Error?e.message:String(e)}if(plan.sourceNode)banNode(plan.targetNode,Number(getSetting('automation.ban_minutes',360)),error instanceof Error?error.message:String(error));run('UPDATE switch_plans SET status=?,rollback_json=?,error=?,completed_at=?,updated_at=? WHERE id=?',rollbackError?'rollback_failed':'rolled_back',JSON.stringify({...backup,rollbackError}),error instanceof Error?error.message:String(error),nowIso(),nowIso(),planId);run('DELETE FROM locks WHERE name=? AND owner=?',lockName,owner);throw Object.assign(error instanceof Error?error:new Error(String(error)),{code:(error as any)?.code||'SWITCH_FAILED',details:{rollbackError}})}}
