import { all, one, run, transaction } from '../db.ts'
import { createTunnel, deleteTunnel, listTunnelsRaw, normalizeTunnel } from '../providers/chmlfrp.ts'
import { getSetting, putCache } from '../state.ts'
import { id, json, nowIso, sha256, text } from '../util.ts'

function managedName(name:string){const prefix=text(getSetting('chmlfrp.managed_prefix','[ashan-frp]'));return name.startsWith(prefix)?name:`${prefix}${name}`}
function strippedName(name:string){const prefix=text(getSetting('chmlfrp.managed_prefix','[ashan-frp]'));return name.startsWith(prefix)?name.slice(prefix.length):name}
export function listDesiredTunnels(){return all('SELECT * FROM desired_tunnels ORDER BY name').map((r)=>({...r,enabled:!!r.enabled,managed:!!r.managed,encryption:!!r.encryption,compression:!!r.compression,metadata:json(r.metadata_json,{})}))}
export function listObservedTunnels(){return all('SELECT * FROM observed_tunnels ORDER BY name,node_name').map((r)=>({...r,managed:!!r.managed,raw:json(r.raw_json,{})}))}
export function saveDesiredTunnel(input:any){
  const name=text(input.name)
  if(!name)throw Object.assign(new Error('隧道名称不能为空'),{code:'TUNNEL_NAME_REQUIRED',status:400})
  const protocol=text(input.protocol||'tcp').toLowerCase()
  if(!['tcp','udp','http','https'].includes(protocol))throw Object.assign(new Error('协议必须为tcp/udp/http/https'),{code:'TUNNEL_PROTOCOL_INVALID',status:400})
  const localPort=Number(input.localPort||input.local_port)
  if(!Number.isInteger(localPort)||localPort<1||localPort>65535)throw Object.assign(new Error('本地端口无效'),{code:'LOCAL_PORT_INVALID',status:400})
  const remoteRaw=input.remotePort??input.remote_port
  const remotePort=remoteRaw==null||remoteRaw===''?null:Number(remoteRaw)
  const domain=text(input.domain)||null
  if(['tcp','udp'].includes(protocol)&&remotePort!=null&&(!Number.isInteger(remotePort)||remotePort<1||remotePort>65535))throw Object.assign(new Error('远程端口无效'),{code:'REMOTE_PORT_INVALID',status:400})
  if(['http','https'].includes(protocol)&&!domain)throw Object.assign(new Error('HTTP/HTTPS隧道必须填写域名'),{code:'TUNNEL_DOMAIN_REQUIRED',status:400})
  const requestedId=text(input.id)
  const byId=requestedId?one('SELECT * FROM desired_tunnels WHERE id=?',requestedId):null
  if(requestedId&&!byId)throw Object.assign(new Error('期望隧道不存在'),{code:'DESIRED_TUNNEL_NOT_FOUND',status:404})
  const byName=one('SELECT * FROM desired_tunnels WHERE name=?',name)
  if(byName&&byId&&byName.id!==byId.id)throw Object.assign(new Error('隧道名称已被其他记录使用'),{code:'TUNNEL_NAME_CONFLICT',status:409})
  const current=byId||byName,tid=current?.id||id(),now=nowIso()
  const values=[name,protocol,text(input.localIp||input.local_ip)||'127.0.0.1',localPort,remotePort,domain,input.encryption?1:0,input.compression===false?0:1,text(input.extraParams||input.extra_params),input.enabled===false?0:1,input.managed===false?0:1,text(input.healthUrl||input.health_url)||null,JSON.stringify(input.metadata||{}),now,tid]
  if(current)run('UPDATE desired_tunnels SET name=?,protocol=?,local_ip=?,local_port=?,remote_port=?,domain=?,encryption=?,compression=?,extra_params=?,enabled=?,managed=?,health_url=?,metadata_json=?,updated_at=? WHERE id=?',...values)
  else run('INSERT INTO desired_tunnels(id,name,protocol,local_ip,local_port,remote_port,domain,encryption,compression,extra_params,enabled,managed,health_url,metadata_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',tid,...values.slice(0,13),now,now)
  return one('SELECT * FROM desired_tunnels WHERE id=?',tid)
}
export function deleteDesiredTunnel(idValue:string){const result=run('DELETE FROM desired_tunnels WHERE id=?',idValue);if(!result.changes)throw Object.assign(new Error('期望隧道不存在'),{code:'DESIRED_TUNNEL_NOT_FOUND',status:404});return{deleted:true,id:idValue}}
export async function syncObservedTunnels(){const raw=await listTunnelsRaw(),now=nowIso(),normalized=raw.map(normalizeTunnel).filter((x:any)=>x.name);transaction(()=>{run('DELETE FROM observed_tunnels');for(const t of normalized)run('INSERT INTO observed_tunnels(id,external_id,name,node_name,protocol,local_ip,local_port,remote_port,domain,remote_ip,managed,raw_json,observed_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',id(),t.externalId||null,t.name,t.nodeName||null,t.protocol||null,t.localIp||null,t.localPort||null,t.remotePort||null,t.domain||null,t.remoteIp||null,t.managed?1:0,JSON.stringify(t.raw),now)});putCache('tunnels.observed','chmlfrp',normalized,180);return{count:normalized.length,tunnels:normalized}}
function desiredHash(row:any,targetNode:string){return sha256(JSON.stringify({name:managedName(row.name),node:targetNode,protocol:row.protocol,localIp:row.local_ip,localPort:row.local_port,remotePort:row.remote_port||null,domain:row.domain||null,encryption:!!row.encryption,compression:!!row.compression,extraParams:row.extra_params||''}))}
function observedHash(row:any){return sha256(JSON.stringify({name:row.name,node:row.node_name||'',protocol:row.protocol||'',localIp:row.local_ip||'',localPort:Number(row.local_port||0),remotePort:Number(row.remote_port||0)||null,domain:row.domain||null}))}
export function buildTunnelPlan(targetNode?:string,options:{cleanupOrphans?:boolean}={}){const node=targetNode||text(getSetting('runtime.current_node',''));if(!node)throw Object.assign(new Error('尚未选择目标节点'),{code:'TARGET_NODE_REQUIRED',status:400});const desired=listDesiredTunnels().filter((x:any)=>x.enabled),observed=listObservedTunnels(),byName=new Map(observed.map((x:any)=>[strippedName(x.name),x])),actions:any[]=[],matched:string[]=[];for(const d of desired){const o=byName.get(d.name);const expected={...d,name:managedName(d.name),node};if(!o){actions.push({type:'create',desiredId:d.id,name:d.name,targetNode:node,expected,risk:'medium',reason:'远端缺失'});continue}byName.delete(d.name);const dh=desiredHash(d,node),oh=observedHash(o);if(dh===oh){matched.push(d.name);continue}actions.push({type:'replace',desiredId:d.id,name:d.name,targetNode:node,externalId:o.external_id,previous:o,expected,risk:'high',reason:o.node_name!==node?'节点不同':'配置不同'})}for(const [name,o] of byName){if(o.managed&&options.cleanupOrphans)actions.push({type:'delete_orphan',name,externalId:o.external_id,previous:o,risk:'high',reason:'本地无期望定义'});else if(o.managed)actions.push({type:'orphan',name,externalId:o.external_id,previous:o,risk:'low',reason:'仅标记，不自动删除'})}const limit=Number(getSetting('chmlfrp.tunnel_limit',16)),used=observed.length,creates=actions.filter((x)=>x.type==='create').length,blocked=used+creates>limit?creates-(limit-used):0;return{id:id(),targetNode:node,used,limit,remaining:Math.max(0,limit-used),matched,actions,blocked,generatedAt:nowIso(),risk:actions.some((x)=>x.risk==='high')?'high':actions.length?'medium':'low'}}
async function createFromDesired(row:any,targetNode:string){return createTunnel({name:row.name,protocol:row.protocol,localIp:row.local_ip,localPort:row.local_port,remotePort:row.remote_port,domain:row.domain,encryption:!!row.encryption,compression:!!row.compression,extraParams:row.extra_params},targetNode)}
export async function applyTunnelPlan(plan:any,event:(type:string,message:string,payload?:any)=>void=()=>{}){if(plan.blocked>0)throw Object.assign(new Error(`隧道容量不足，受阻动作${plan.blocked}个`),{code:'TUNNEL_CAPACITY_BLOCKED',status:409,details:plan});const results:any[]=[];for(const action of plan.actions){if(action.type==='orphan'){results.push({...action,status:'skipped'});continue}if(action.type==='create'){event('tunnel.create',`创建 ${action.name}`,action);const desired=one('SELECT * FROM desired_tunnels WHERE id=?',action.desiredId);try{const response=await createFromDesired(desired,plan.targetNode);results.push({...action,status:'succeeded',response})}catch(e){results.push({...action,status:'failed',error:e instanceof Error?e.message:String(e)});throw e}continue}if(action.type==='replace'){event('tunnel.replace.delete',`删除旧隧道 ${action.name}`,action);const desired=one('SELECT * FROM desired_tunnels WHERE id=?',action.desiredId);if(!desired)throw Object.assign(new Error('期望隧道已删除'),{code:'DESIRED_TUNNEL_MISSING'});await deleteTunnel(action.externalId);try{event('tunnel.replace.create',`在 ${plan.targetNode} 重建 ${action.name}`,action);const response=await createFromDesired(desired,plan.targetNode);results.push({...action,status:'succeeded',response})}catch(error){event('tunnel.replace.rollback',`重建失败，尝试恢复旧隧道 ${action.name}`,action);try{const p=action.previous;await createTunnel({name:strippedName(p.name),protocol:p.protocol,localIp:p.local_ip,localPort:p.local_port,remotePort:p.remote_port,domain:p.domain,encryption:false,compression:true,extraParams:''},p.node_name);results.push({...action,status:'rolled_back',error:error instanceof Error?error.message:String(error)})}catch(rollback){results.push({...action,status:'rollback_failed',error:error instanceof Error?error.message:String(error),rollbackError:rollback instanceof Error?rollback.message:String(rollback)})}throw error}continue}if(action.type==='delete_orphan'){event('tunnel.delete',`清理孤儿隧道 ${action.name}`,action);await deleteTunnel(action.externalId);results.push({...action,status:'succeeded'})}}
await syncObservedTunnels();return{applied:true,results}}
